services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prd
    environment:
      - TZ=Asia/Tokyo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"